name: CI

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Echo ref
      run: echo ${{ github.ref }}

    - name: Echo event name
      run: echo ${{ github.event_name }}

    - name: Build parent
      uses: docker/build-push-action@v1.0.1
      with:
        repository: psavery/test
        tags: parent
        path: ./parent
        add_git_labels: true
        push: false

    - name: Build child
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: psavery/test
        tags: child
        path: ./child
        add_git_labels: true
        push: ${{ !startsWith(github.ref, 'refs/pull/') }}
